import java.nio.file.Files

for (def sourceSet in [
	sourceSets.main,
	sourceSets.client
]) {
	// We have to capture the source set name for the lazy string literals,
	// otherwise it'll just be whatever the last source set is in the list.
	def sourceSetName = sourceSet.name
	def taskName = sourceSet.getTaskName('generate', 'PackageInfos')
	def task = tasks.register(taskName, GeneratePackageInfos) {
		group = 'terraform'
		description = "Generates package-info files for $sourceSetName packages."

		// Only apply to default source directory since we also add the generated
		// sources to the source set.
		sourceRoot = file("src/$sourceSetName/java")
		header = rootProject.file('HEADER')
		outputDir = file("src/generated/$sourceSetName")
	}
	sourceSet.java.srcDir task

	def cleanTask = tasks.register(sourceSet.getTaskName('clean', 'PackageInfos'), Delete) {
		group = 'terraform'
		delete file("src/generated/$sourceSetName")
	}
	clean.dependsOn cleanTask
}

abstract class GeneratePackageInfos extends DefaultTask {
	@InputFile
	File header

	@Input
	abstract Property<String> getProjectName()

	@SkipWhenEmpty
	@InputDirectory
	final DirectoryProperty sourceRoot = project.objects.directoryProperty()

	@OutputDirectory
	final DirectoryProperty outputDir = project.objects.directoryProperty()

	GeneratePackageInfos() {
		projectName.set(project.name)
	}

	@TaskAction
	def run() {
		def output = outputDir.get().asFile.toPath()
		output.deleteDir()
		def headerText = header.readLines().join("\n") // normalize line endings
		def root = sourceRoot.get().asFile.toPath()

		root.eachDirRecurse {
			def containsJava = Files.list(it).any {
				Files.isRegularFile(it) && it.fileName.toString().endsWith('.java')
			}

			if (!containsJava) {
				return
			}

			// Check existing package-info.java to ensure it has @NullMarked
			def existingPackageInfo = it.resolve('package-info.java')
			if (Files.exists(existingPackageInfo)) {
				if (!existingPackageInfo.text.contains("@NullMarked")) {
					throw new RuntimeException("package-info.java ${existingPackageInfo} is missing @NullMarked annotation.")
				}

				return
			}

			def relativePath = root.relativize(it)
			def target = output.resolve(relativePath)
			Files.createDirectories(target)

			def packageName = relativePath.toString().replace(File.separator, '.')

			def implPattern = /^(com[\/\\]terraformersmc[\/\\]terraform[\/\\][^\/\\]+[\/\\](impl|mixin))/
			def isImpl = relativePath.toString() ==~ implPattern

			target.resolve('package-info.java').withWriter {
				if (isImpl) {
					it.write("""$headerText
						|/**
						| * Implementation code for ${projectName.get()}.
						| */
						|@ApiStatus.Internal
						|@NullMarked
						|package $packageName;
						|
						|import org.jetbrains.annotations.ApiStatus;
						|import org.jspecify.annotations.NullMarked;
						|""".stripMargin())
				} else {
					it.write("""$headerText
						|/**
						| * API code for ${projectName.get()}.
						| */
						|@NullMarked
						|package $packageName;
						|
						|import org.jspecify.annotations.NullMarked;
						|""".stripMargin())
				}
			}
		}
	}
}
